sudo: required
services: 
  - docker

before_install:
  - docker build -t csolorio/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run csolorio/react-test npm test -- --coverage

after_success:
  - docker build -t csolorio/multi-client ./client
  - docker build -t csolorio/multi-nginx ./nginx
  - docker build -t csolorio/multi-server ./server
  - docker build -t csolorio/multi-worker ./worker
  # Log in to docker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push  csolorio/multi-client
  - docker push  csolorio/multi-nginx
  - docker push  csolorio/multi-server
  - docker push  csolorio/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-1-989373873448
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
